### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nuuralifah**
'garfu' cuit2 sikit je kot

### CODE REVIEW

**Comment by nuuralifah** [comment]
first time explore sebab nak tshirt muahaha!

**Comment by ApOgEE** [comment]
hehehe... rajin sungguh membetulkan Caps. :smile: open la pull request ni, boleh saya merge pembetulan tu

**Comment by ApOgEE** [comment]
hahaha... dah merge, tapi gambar hilang. suka2 hati dia je pi buang exclamation mark tu... hahaha

**Comment by nuuralifah** [comment]
haha.. tak tau nak fork ape..sat ea..

On Thu, Jun 25, 2015 at 12:31 AM, M. Fauzilkamil Zainuddin <
notifications@github.com> wrote:

> Merged #36 https://github.com/ApOgEE/TempahTeeGit/pull/36.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ApOgEE/TempahTeeGit/pull/36#event-339141501.

## 

*regards, *

_Miss. Nuur Alifah Binti Roslan_
_M.Computer Security (UPM), B.Comp.Science(Multimedia)_ _(UPM)_

_Information Security LabFaculty Science Computer and Information
TechnologyUniversiti Putra Malaysia43400, UPM Serdang,Selangor Darul Ehsan,
MALAYSIAmobile: *_ +60137281224 *
_email: nuuralifahroslan@gmail.com nuuralifahroslan@gmail.com_
_research blog: www.growingyourthought.wordpress.com
http://www.growingyourthought.wordpress.com_

**Comment by ApOgEE** [comment]
takpe dah betulkan dah

**Comment by nuuralifah** [comment]
eh! terbuang jadik hilang gamba ea? haha

maap! try n error jer

On Thu, Jun 25, 2015 at 12:35 AM, M. Fauzilkamil Zainuddin <
notifications@github.com> wrote:

> hahaha... dah merge, tapi gambar hilang. suka2 hati dia je pi buang
> exclamation mark tu... hahaha
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ApOgEE/TempahTeeGit/pull/36#issuecomment-114935367.

## 

*regards, *

_Miss. Nuur Alifah Binti Roslan_
_M.Computer Security (UPM), B.Comp.Science(Multimedia)_ _(UPM)_

_Information Security LabFaculty Science Computer and Information
TechnologyUniversiti Putra Malaysia43400, UPM Serdang,Selangor Darul Ehsan,
MALAYSIAmobile: *_ +60137281224 *
_email: nuuralifahroslan@gmail.com nuuralifahroslan@gmail.com_
_research blog: www.growingyourthought.wordpress.com
http://www.growingyourthought.wordpress.com_

**Comment by ApOgEE** [comment]
hahaha.. no problem... ni la masanya nak belajar :smile:

**Comment by nuuralifah** [comment]
tu la pasal.. klu tak ..tak denyer nak godek github nie.. sign up jer..
aish tetiba rasa nak join plak event 30 jun nie..macam menarik jer

On Thu, Jun 25, 2015 at 12:37 AM, M. Fauzilkamil Zainuddin <
notifications@github.com> wrote:

> hahaha.. no problem... ni la masanya nak belajar [image: :smile:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ApOgEE/TempahTeeGit/pull/36#issuecomment-114936039.

## 

*regards, *

_Miss. Nuur Alifah Binti Roslan_
_M.Computer Security (UPM), B.Comp.Science(Multimedia)_ _(UPM)_

_Information Security LabFaculty Science Computer and Information
TechnologyUniversiti Putra Malaysia43400, UPM Serdang,Selangor Darul Ehsan,
MALAYSIAmobile: *_ +60137281224 *
_email: nuuralifahroslan@gmail.com nuuralifahroslan@gmail.com_
_research blog: www.growingyourthought.wordpress.com
http://www.growingyourthought.wordpress.com_

**Comment by ApOgEE** [comment]
Event tu 11 Julai lah... hahahaha... silap info tu. 30 Jun ni tutup pre-order baju ni.

**Comment by nuuralifah** [comment]
eh! aah ok2 will check again the details.. dah mamai..

2015-06-25 0:40 GMT+08:00 M. Fauzilkamil Zainuddin <notifications@github.com

> :
> 
> Event tu 11 Julai lah... hahahaha... silap info tu. 30 Jun ni tutup
> pre-order baju ni.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ApOgEE/TempahTeeGit/pull/36#issuecomment-114937419.

## 

*regards, *

_Miss. Nuur Alifah Binti Roslan_
_M.Computer Security (UPM), B.Comp.Science(Multimedia)_ _(UPM)_

_Information Security LabFaculty Science Computer and Information
TechnologyUniversiti Putra Malaysia43400, UPM Serdang,Selangor Darul Ehsan,
MALAYSIAmobile: *_ +60137281224 *
_email: nuuralifahroslan@gmail.com nuuralifahroslan@gmail.com_
_research blog: www.growingyourthought.wordpress.com
http://www.growingyourthought.wordpress.com_

**Pull request merged**
